### ISSUE TITLE
communication protocol

### ISSUE THREAD

**Issue by MiccWan** [MiccWan/knect#2]
# Develop the following API

### Events

* [ ] login(future work)

* [x] `send_invitation({ playerId }) requires player.isInRoom()`

* [x] `join_room({ roomId })`

* [x] `leave_room() requires player.isInRoom()`
* [x] `leave_game() requires player.isInRoom() room.playerInGame(player.id)`

* [x] `send_chat({ msg })`

* [x] `join_game({ player: PlayerSideType }) requires player.isInRoom()`

* [ ] `game_place`

### Requests

* [x] `get_room_list()`

* [x] `get_player_list()`

* [x] `create_room({ name }) returns { id }`

### Events

* [x] `update_room_list({ type, room: { id, name } })`

* [x] `update_player_list({ type, id, name })`

* [x] `notify_invitation({ playerId, roomId })`

* [x] `notify_chat({ name, msg, time })`

* [ ] `announce`

* [x] `notify_chat({ name, msg, time })`

* [x] <del>`notify_player_join_room({ playerId })`</del> (deprecated)

* [x] `notify_player_side({ type, id, side: PlayerSideType })`

* [ ] `game_notify_placed`

* [ ] `notify_win`

* [ ] `notify_kicked`

### Requests

* [ ] `confirm_start`

# Wrap them into a `SocketWrapper` & add the above event names to `knect-common`

* Example

```js
const SocketEvents = {
  GetRoomList: 'get_room_list'
}
```

* Usage

```js
const server = new SocketWrapper();
await server.request(SocketEvents.GetRoomList);
```

```js
const server = new SocketWrapper();
server.on(SocketEvents.NotifyWin, handleWin);

function handleWin({ winner }) {
  // code here...
}
```

**Comment by MiccWan** [comment]
@edisonhello
- [ ] `joinGame()` should take an argument that specifies which sit he wants to join. (and maybe rename to `joinTable` if not time consuming)
- [ ] `joinRoom()` should be a request that sends room data on successful.
- [ ] `createRoom()` should sends room data on successful.
- [ ] ` getRoomList()` should return more information including game status and players inside(not work now).

@MiccWan 
- [ ] merge `PlayerSideType` and `RoleType`

**Comment by xco1014** [comment]
- [x]  `createRoom()` should not return undefined .
- [x] may need leave room function.
- [x] chat work unexpectedly.(Room's msg will send to lobby)
- [x] `updatePlayerList()` send twice when new users login
- [x] `update_room_list` should send more information including game status and players inside.
- [x] `joinRoom()` has error.
